// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeD1BPhY7ZRHcA8NJkV0BdzPoQR4ZqS4',
    appId: '1:383150421118:web:709d1fe91ee5181d1ed42f',
    messagingSenderId: '383150421118',
    projectId: 'ezborrow-69a14',
    authDomain: 'ezborrow-69a14.firebaseapp.com',
    storageBucket: 'ezborrow-69a14.appspot.com',
    measurementId: 'G-1NN06NQ69T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvPvuIneOQV8i4y4uC9OY7jw-Flmv0B8',
    appId: '1:383150421118:android:f3786873ee36896f1ed42f',
    messagingSenderId: '383150421118',
    projectId: 'ezborrow-69a14',
    storageBucket: 'ezborrow-69a14.appspot.com',
    
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcyl6YlIAYAA49jz6zYFGZyK8VN6TH98',
    appId: '1:383150421118:ios:db1de77bf9e9a1e41ed42f',
    messagingSenderId: '383150421118',
    projectId: 'ezborrow-69a14',
    storageBucket: 'ezborrow-69a14.appspot.com',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcyl6YlIAYAA49jz6zYFGZyK8VN6TH98',
    appId: '1:383150421118:ios:f4db8c863dd17ec81ed42f',
    messagingSenderId: '383150421118',
    projectId: 'ezborrow-69a14',
    storageBucket: 'ezborrow-69a14.appspot.com',
    iosBundleId: 'com.example.lms.RunnerTests',
  );
}
